cornershop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls'))

]

menu/urls.py
from django.urls import path

from . import views_meal, views_menu, views_employee_menu


urlpatterns = [
    # Meals
    path('meal/index/', views_meal.ListMeal.as_view(), name='meal_list'),
    path('meal/new/', views_meal.CreateMeal.as_view(), name='meal_create'),
    path('meal/update/<int:pk>/', views_meal.UpdateMeal.as_view(), name='meal_update'),
    path('meal/delete/<int:pk>/', views_meal.DeleteMeal.as_view(), name='meal_delete'),

    #Menu
    path('menu/index/', views_menu.ListMenu.as_view(), name='menu_list'),
    path('menu/new/', views_menu.CreateMenu.as_view(), name='menu_create'),
    path('menu/update/<int:pk>/', views_menu.UpdateMenu.as_view(), name='menu_update'),
    path('menu/delete/<int:pk>/', views_menu.DeleteMenu.as_view(), name='menu_delete'),

    path('menu/<str:uid>/', views_menu.TodayMenu.as_view(), name='menu_today'),

    # meal requests
    path('meal/requested/', views_employee_menu.ListEmployeeMenu.as_view(), name='requested_list'),
    path('meal/requested/<str:duedate>/', views_employee_menu.ListEmployeeMenu.as_view(), name='requested_list')

]

menu/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

from django.core.exceptions import ValidationError

# Create your models here.

User = get_user_model()

class Meal(models.Model):
    """Nombres y descripciones de los platos que se servirán en el menú"""
    name = models.CharField(max_length=48, unique=True, help_text='Nombre del plato')
    description = models.TextField(max_length=500, blank=True, help_text='Detalle de los ingredientes')

    def __str__(self):
        return self.name


class Employee(models.Model):
    """Usuario del sistema es potencialmente un 'empleado' que necesita
    ser alimentado"""
    user = models.OneToOneField(User, help_text='Usuario', on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=50, help_text='Número de teléfono')

class Menu(models.Model):
    """Corresponde al menú para un día específico"""

    due_date = models.DateField(default=timezone.now, unique=True)
    meals = models.ManyToManyField(Meal)
    employees = models.ManyToManyField(Employee, through='Employee_Menu')

    uuid = models.UUIDField(
        editable=False,
        default=uuid4,
        unique=True
        #primary_key=True
    )

    def __str__(self):

        due_date = self.due_date.strftime('%x')

        return f"Menú del {due_date}"

    class Meta:
        ordering = ['-due_date']

    def get_absolute_url(self):
        return reverse('menu_today', args=[self.uuid])


class Employee_Menu(models.Model):
    """Esta tabla guarda la selección de menú de un empleado.

    Se hace referencia al menú y al empleado, permitiendo a éste
    especificar alguna personalización.

    Importante: En el campo `meal_choice` se guarda directamente la opción
    elegida del menú. Aquí deliberadamente se desnormaliza `meal`
    para mantener un registro histórico de la opción seleccionada
    por el empleado, así no se actualiza si la referencia a `meal`
    cambiara en un futuro.
    """

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    meal_choice = models.CharField(max_length=255, null=False)
    customization = models.TextField(max_length=500, blank=True,
                                     help_text='Desea especificar alguna instrucción especial para tu comida?')

    def validate_unique(self, *args, **kwargs):
        """valida que exista solamente un menú registrado para ese empleado ese día"""
        super(Employee_Menu, self).validate_unique(*args, **kwargs)

        if self.__class__.objects.\
                filter(employee=self.employee, menu__due_date=self.menu.due_date).\
                exists():
            raise ValidationError(
                message='Este empleado ya tiene un menú registrado para esta fecha',
                code='unique_together',
            )

menu/forms.py
from django import forms
from .models import Meal, Menu, Employee, Employee_Menu

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = '__all__'


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['due_date', 'meals']


class EmployeeMenuForm(forms.ModelForm):
    class Meta:
        model = Employee_Menu
        fields = ['menu', 'meal_choice', 'customization']

templates/base/layout.html
{#{% load staticfiles %}#}
<!DOCTYPE html>
<html class="has-background-light">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
{% load static %}

    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">
</head>

<body>

<nav class="navbar is-dark is-spaced">
    <div class="navbar-brand">
        <a href="{% url 'meal_list' %}" class="navbar-item">
            Meal Delivery
        </a>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navigation">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navigation" class="navbar-menu">
        <div class="navbar-start">
            <a href="{% url 'meal_list' %}" class="navbar-item">Comidas</a>
            <a href="{% url 'menu_list' %}" class="navbar-item">Menu</a>

        </div>

        <div class="navbar-end">

            {% if user.is_authenticated %}
             <a class="navbar-item" href="#">Usuario: {{ user.username }}</a>
            {% else %}
                 <a class="navbar-item" href="#">Iniciar sesión</a>

            {% endif %}


        </div>


    </div>

</nav>

<div class="section">

    <div class="container">


        {% block content %}

        {% endblock %}

    </div>

</div>

<script src="https://unpkg.com/mithril/mithril.js"></script>

<script type="text/javascript">
    {% include 'javascript_app.js' %}

    /* helper de bulma para mostrar el menú principal cuando activa el burger-menu */
    document.addEventListener('DOMContentLoaded', () => {

        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {

            // Add a click event on each of them
            $navbarBurgers.forEach( el => {
                el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });
        }

    });

</script>

</body>
</html>

templates/employee_menu/list.html
{% extends 'base/layout.html' %}


{% block content %}




    {% for data in object_list %}

        {{ data.employee.user.email }}

        {{ data.menu }}

    {% endfor %}

{% endblock %}

templates/generic_confirm.html
{% extends 'base/layout.html' %}

{% block content %}

    <div class="notification is-warning">
        <form method="post">
            {% csrf_token %}

            <h2 class="title">Confirma que desea eliminar "{{ object }}"?</h2>

            <button class="button is-dark is-pulled-right" type="submit">Si, confirmar</button>
            <a href="{% url 'meal_list' %}" class="button">No, anular</a>

        </form>
    </div>
{% endblock %}

templates/meal/list.html
{% extends 'base/layout.html' %}


{% block content %}

    <a href="{% url 'meal_create' %}" class="button is-link is-pulled-right">Agregar</a>
    <h1 class="title">Comidas disponibles</h1>
    <div class="table-container box">
        <table class="table is-fullwidth is-hoverable">

            <tr class="thead">

                <th>Nombre</th>
                <th>Descripción</th>
                <th></th>
            </tr>

            <tbody>
            {% for meal in meal_list %}

                <tr>
                    <td>

                        <a href="#">{{ meal.name|capfirst }}</a>


                    </td>
                    <td>{{ meal.description|capfirst }}</td>

                    <td>


                        <a class="button is-warning" href="{% url 'meal_update' meal.pk %}">
                            editar
                        </a>

                    </td>
                </tr>

            {% endfor %}
            </tbody>



        </table>

    </div>
{% endblock %}

templates/meal/new.html
{% extends 'base/layout.html' %}

{% block content %}

    <div class="columns">
        <div class="column">
            <div class="box">
                <h1 class="title">{{ title }}</h1>
                <form method="post">
                    {% csrf_token %}

                    <div class="field">
                        <label for="name" class="label">Nombre</label>
                        <div class="control">
                            <input value="{{ form.name.value | default_if_none:"" }}" class="input" type="text" name="name" maxlength="140" required="" id="id_name">
                        </div>
                        {% if form.name.errors %}
                            <p class="help is-danger">
                                {% for error in form.name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>

                    <div class="field">
                        <label for="description" class="label">Descripción</label>
                        <div class="control">
                            <textarea class="textarea" name="description" placeholder="Detalle, ingredientes, especificaciones, etc." cols="40" rows="10" maxlength="500" id="id_description">
                                {{ form.description.value | default_if_none:'' }}
                            </textarea>
                        </div>
                        {% if form.description.errors %}
                            <p class="help is-danger">
                                {% for error in form.description.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>

                    <div class="field block is-align-content-end">



                        {% if form.instance.pk %}

                            <input class="button is-primary" type="submit" value="Modificar">


                            <a class="button is-pulled-right is-danger" href="{% url 'meal_delete' form.instance.pk %}">
                                Eliminar
                            </a>

                        {%  else %}

                            <input class="button is-primary" type="submit" value="Agregar">


                        {% endif %}

                        <a href="{% url 'meal_list' %}" class="button">Cancelar</a>


                    </div>


                </form>

            </div>
        </div>





    </div>

{% endblock %}

templates/menu/list.html
{% extends 'base/layout.html' %}


{% block content %}

    <a href="{% url 'menu_create' %}" class="button is-link is-pulled-right">Agregar</a>
    <h1 class="title">Menús disponibles</h1>
    <div class="table-container box">
        <table class="table is-fullwidth is-hoverable">

            <tr class="thead">

                <th>Fecha</th>
                <th>Opciones</th>
                <th></th>
            </tr>

            <tbody>
            {% for menu in menu_list %}

                <tr>
                    <td>
                        <a href="{{ menu.get_absolute_url }}">
                            {{ menu.due_date }}
                        </a>

                    </td>
                    <td>

                        <div class="menu content">

                            <ol class="menu-list">

                                {% for meal in menu.meals.all %}

                                    <li><a class="is-capitalized" href="{% url 'meal_update' meal.id %}">{{ meal.name }}</a></li>

                                {% endfor %}
                            </ol>
                        </div>
                    </td>

                    <td>


                        <a class="button is-pulled-right is-warning" href="{% url 'menu_update' menu.pk %}">
                            Editar
                        </a>

                    </td>
                </tr>

            {% endfor %}
            </tbody>



        </table>

    </div>
{% endblock %}

templates/menu/new.html
{% extends 'base/layout.html' %}

{% block content %}


    <div class="box">
        <h1 class="title">{{ title }}</h1>
        <form method="post">
            {% csrf_token %}


            <div class="field">
                <label for="id_due_date" class="label">Fecha</label>
                <div class="control">
                    <input class="input"
                           value="{{ form.due_date.value | date:"Y-m-d" | default_if_none:"" }}"
                           type="date" name="due_date" required="true" id="id_due_date" />

                </div>
                {% if form.due_date.errors %}
                    <p class="help is-danger">
                        {% for error in form.due_date.errors %}
                            {{ error }}
                        {% endfor %}
                    </p>
                {% endif %}
            </div>


            <div class="field">
                <label for="" class="label"></label>

                <div class="control">

                    <div class="select is-multiple is-fullwidth">
                        {{ form.meals }}
                    </div>
                </div>

            </div>



            <div class="field">


                {% if form.instance.pk %}

                    <input class="button is-primary" type="submit" value="Modificar">


                    <a class="button is-pulled-right is-danger" href="{% url 'menu_delete' form.instance.pk %}">
                        Eliminar
                    </a>

                {%  else %}

                    <input class="button is-primary" type="submit" value="Agregar">


                {% endif %}

                <a href="{% url 'menu_list' %}" class="button">Cancelar</a>


            </div>


        </form>

    </div>

{% endblock %}

templates/menu/view.html
{% extends 'base/layout.html' %}


{% block content %}

    <div class="box">

        {% for error in form.non_field_errors %}
            <div class="panel-block has-background-warning has-text-centered">
                {{ error|escape }}
            </div>
        {% endfor %}
        <form method="post">


            <h1 class="title has-text-centered">{{ menu}} {{ title }}</h1>
            <h2 class="subtitle">Selecciona tu comida

                {%  if form.errors %}

                    {% for f in form %}

                        {% for e in f.errors %}
                            <p class="help is-danger">{{ e }}</p>
                        {% endfor %}
                    {% endfor %}

                {% endif %}



            </h2>

            {% csrf_token %}



            {% for meal in menu.meals.all %}

                <div class="field">


                    <div class="control">


                        <label class="radio">

                            <input type="radio" value="{{ meal.name }}" name="meal_choice" />
                            {{ meal.name|capfirst }}


                        </label>
                        <div class="help">
                            {{ meal.description }}
                        </div>


                    </div>


                </div>


            {% endfor %}

            <div class="field">
                <div class="control">
                    <label class="radio">
                        <input type="radio" name="meal_choice" value="NADA" />
                        No quiero almuerzo, gracias
                    </label>
                </div>
            </div>
        {% if user.is_authenticated %}
            <div class="field">
                <div class="control">
                    <label for="customization">Especifica tu personalización</label>
                    <textarea name="customization" id="customization" class="textarea"></textarea>
                </div>
            </div>


            <div class="block pt-4 has-text-right">

                <input type="hidden" name="menu" value="{{ menu.id }}">

                <button class="button is-success" type="submit">Confirmar</button>
            </div>

{% endif %}


        </form>
    </div>
{% endblock %}